--
-- PostgreSQL database dump
--

\restrict vaOd86Lb50qL42XJwglZSbliLmH7pBTfuDFgBnEUq7UWhqpSv2b8PqROb8KlMq3

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.achievements (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    description text,
    title character varying(255) NOT NULL,
    xp_reward integer NOT NULL
);


ALTER TABLE public.achievements OWNER TO postgres;

--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_set_words; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.custom_set_words (
    id bigint NOT NULL,
    set_id uuid NOT NULL,
    word_id integer NOT NULL
);


ALTER TABLE public.custom_set_words OWNER TO postgres;

--
-- Name: custom_set_words_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.custom_set_words ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_set_words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_sets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.custom_sets (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    is_public boolean NOT NULL,
    title character varying(255) NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.custom_sets OWNER TO postgres;

--
-- Name: duels; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.duels (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    creator_accuracy double precision,
    finished_at timestamp(6) without time zone,
    opponent_accuracy double precision,
    status character varying(255) NOT NULL,
    word_ids text,
    creator_id uuid NOT NULL,
    lang_from_id integer NOT NULL,
    lang_to_id integer NOT NULL,
    opponent_id uuid NOT NULL,
    winner_id uuid,
    CONSTRAINT duels_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'IN_PROGRESS'::character varying, 'FINISHED'::character varying, 'DECLINED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.duels OWNER TO postgres;

--
-- Name: friendships; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friendships (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    addressee_id uuid NOT NULL,
    requester_id uuid NOT NULL,
    CONSTRAINT friendships_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'BLOCKED'::character varying])::text[])))
);


ALTER TABLE public.friendships OWNER TO postgres;

--
-- Name: languages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.languages (
    id integer NOT NULL,
    code character varying(10) NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.languages OWNER TO postgres;

--
-- Name: languages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.languages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.languages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessions (
    id uuid NOT NULL,
    correct integer NOT NULL,
    duration_seconds integer NOT NULL,
    finished_at timestamp(6) without time zone,
    incorrect integer NOT NULL,
    mode character varying(255) NOT NULL,
    started_at timestamp(6) without time zone NOT NULL,
    total_words integer NOT NULL,
    lang_from_id integer NOT NULL,
    lang_to_id integer NOT NULL,
    user_id uuid NOT NULL,
    topic character varying(255),
    CONSTRAINT sessions_mode_check CHECK (((mode)::text = ANY ((ARRAY['MATCHING'::character varying, 'WRITING'::character varying, 'TIME_ATTACK'::character varying, 'SURVIVAL'::character varying, 'BOSS_ROUND'::character varying])::text[])))
);


ALTER TABLE public.sessions OWNER TO postgres;

--
-- Name: translations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.translations (
    id integer NOT NULL,
    example_sentence text,
    translation character varying(255) NOT NULL,
    target_language_id integer NOT NULL,
    word_id integer NOT NULL
);


ALTER TABLE public.translations OWNER TO postgres;

--
-- Name: translations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.translations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.translations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_achievements; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_achievements (
    id uuid NOT NULL,
    earned_at timestamp(6) without time zone NOT NULL,
    achievement_id integer NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.user_achievements OWNER TO postgres;

--
-- Name: user_word_progress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_word_progress (
    id uuid NOT NULL,
    easiness_factor integer NOT NULL,
    error_count integer NOT NULL,
    interval_days integer NOT NULL,
    last_seen timestamp(6) without time zone,
    next_review date NOT NULL,
    repetitions integer NOT NULL,
    status character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    word_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    CONSTRAINT user_word_progress_status_check CHECK (((status)::text = ANY ((ARRAY['LEARNING'::character varying, 'MASTERED'::character varying, 'FORGOTTEN'::character varying])::text[])))
);


ALTER TABLE public.user_word_progress OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id uuid NOT NULL,
    app_language character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    last_active date,
    level integer NOT NULL,
    password_hash character varying(255) NOT NULL,
    streak_days integer NOT NULL,
    subscription_tier character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    xp integer NOT NULL,
    last_freeze_used date,
    CONSTRAINT users_subscription_tier_check CHECK (((subscription_tier)::text = ANY ((ARRAY['FREE'::character varying, 'PREMIUM'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: words; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.words (
    id integer NOT NULL,
    topic character varying(255),
    word character varying(255) NOT NULL,
    language_id integer NOT NULL
);


ALTER TABLE public.words OWNER TO postgres;

--
-- Name: words_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.words ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: custom_set_words custom_set_words_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_set_words
    ADD CONSTRAINT custom_set_words_pkey PRIMARY KEY (id);


--
-- Name: custom_sets custom_sets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_sets
    ADD CONSTRAINT custom_sets_pkey PRIMARY KEY (id);


--
-- Name: duels duels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT duels_pkey PRIMARY KEY (id);


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);


--
-- Name: languages languages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT languages_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: translations translations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translations
    ADD CONSTRAINT translations_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: achievements uk9qqq83lafche8dr9o229kc9tg; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT uk9qqq83lafche8dr9o229kc9tg UNIQUE (code);


--
-- Name: languages ukf6axmaokhmrbmm746866v0uyu; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT ukf6axmaokhmrbmm746866v0uyu UNIQUE (name);


--
-- Name: languages ukmyc139vxcejowe4q8qm3ca5jn; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.languages
    ADD CONSTRAINT ukmyc139vxcejowe4q8qm3ca5jn UNIQUE (code);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: friendships uq_friendship; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT uq_friendship UNIQUE (requester_id, addressee_id);


--
-- Name: custom_set_words uq_set_word; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_set_words
    ADD CONSTRAINT uq_set_word UNIQUE (set_id, word_id);


--
-- Name: user_achievements uq_user_achievement; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT uq_user_achievement UNIQUE (user_id, achievement_id);


--
-- Name: user_word_progress uq_user_word_progress; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_word_progress
    ADD CONSTRAINT uq_user_word_progress UNIQUE (user_id, word_id);


--
-- Name: user_achievements user_achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT user_achievements_pkey PRIMARY KEY (id);


--
-- Name: user_word_progress user_word_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_word_progress
    ADD CONSTRAINT user_word_progress_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: words words_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT words_pkey PRIMARY KEY (id);


--
-- Name: idx_custom_sets_public; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_custom_sets_public ON public.custom_sets USING btree (is_public);


--
-- Name: idx_custom_sets_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_custom_sets_user ON public.custom_sets USING btree (user_id);


--
-- Name: idx_duels_creator; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_duels_creator ON public.duels USING btree (creator_id);


--
-- Name: idx_duels_opponent; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_duels_opponent ON public.duels USING btree (opponent_id);


--
-- Name: idx_duels_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_duels_status ON public.duels USING btree (status);


--
-- Name: idx_friendships_addressee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friendships_addressee ON public.friendships USING btree (addressee_id);


--
-- Name: idx_friendships_requester; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_friendships_requester ON public.friendships USING btree (requester_id);


--
-- Name: idx_sessions_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sessions_user_date ON public.sessions USING btree (user_id, finished_at);


--
-- Name: idx_translations_word_lang; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_translations_word_lang ON public.translations USING btree (word_id, target_language_id);


--
-- Name: idx_user_achievements_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_achievements_user ON public.user_achievements USING btree (user_id);


--
-- Name: idx_users_streak; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_streak ON public.users USING btree (streak_days DESC);


--
-- Name: idx_users_xp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_xp ON public.users USING btree (xp DESC);


--
-- Name: idx_uwp_user_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_uwp_user_created ON public.user_word_progress USING btree (user_id, created_at);


--
-- Name: idx_uwp_user_review; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_uwp_user_review ON public.user_word_progress USING btree (user_id, next_review);


--
-- Name: idx_uwp_word; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_uwp_word ON public.user_word_progress USING btree (word_id);


--
-- Name: idx_words_lang_topic; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_words_lang_topic ON public.words USING btree (language_id, topic);


--
-- Name: duels fk2260mlivmi6xot083h3lj4oti; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT fk2260mlivmi6xot083h3lj4oti FOREIGN KEY (creator_id) REFERENCES public.users(id);


--
-- Name: sessions fk2dw725i0o8kklbm0l2g6kc223; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk2dw725i0o8kklbm0l2g6kc223 FOREIGN KEY (lang_from_id) REFERENCES public.languages(id);


--
-- Name: custom_sets fk2wdc40ibdvq4qgfy0fvgwlcdd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_sets
    ADD CONSTRAINT fk2wdc40ibdvq4qgfy0fvgwlcdd FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: duels fk5nbe04fiksqohutir1w8yepy1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT fk5nbe04fiksqohutir1w8yepy1 FOREIGN KEY (lang_from_id) REFERENCES public.languages(id);


--
-- Name: user_achievements fk6vt5fpu0uta41vny1x6vpk45k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fk6vt5fpu0uta41vny1x6vpk45k FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_achievements fk8ipvec6cs8t3g8515thtlsxuf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_achievements
    ADD CONSTRAINT fk8ipvec6cs8t3g8515thtlsxuf FOREIGN KEY (achievement_id) REFERENCES public.achievements(id);


--
-- Name: duels fk925l4b69507ai51ceker1j4li; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT fk925l4b69507ai51ceker1j4li FOREIGN KEY (opponent_id) REFERENCES public.users(id);


--
-- Name: custom_set_words fkaobg27v5vf7d9thtjrjcahv0i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_set_words
    ADD CONSTRAINT fkaobg27v5vf7d9thtjrjcahv0i FOREIGN KEY (set_id) REFERENCES public.custom_sets(id);


--
-- Name: user_word_progress fkaruauoevlbohih8usngx3o9e2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_word_progress
    ADD CONSTRAINT fkaruauoevlbohih8usngx3o9e2 FOREIGN KEY (word_id) REFERENCES public.words(id);


--
-- Name: friendships fkas6bp8so5n3pfcqtfxt72e1ii; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fkas6bp8so5n3pfcqtfxt72e1ii FOREIGN KEY (requester_id) REFERENCES public.users(id);


--
-- Name: custom_set_words fkcdxm1mhxk10q5cp6pgfmheskg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.custom_set_words
    ADD CONSTRAINT fkcdxm1mhxk10q5cp6pgfmheskg FOREIGN KEY (word_id) REFERENCES public.words(id);


--
-- Name: user_word_progress fkciba19f12lld0spe86k0kgs9i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_word_progress
    ADD CONSTRAINT fkciba19f12lld0spe86k0kgs9i FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: duels fkddfaqrlceoe329sadslcm9yk8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT fkddfaqrlceoe329sadslcm9yk8 FOREIGN KEY (winner_id) REFERENCES public.users(id);


--
-- Name: friendships fkeq5r8dvxs43wkt7or9pdno9av; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fkeq5r8dvxs43wkt7or9pdno9av FOREIGN KEY (addressee_id) REFERENCES public.users(id);


--
-- Name: sessions fkglpm9nl7rcqmp30kt24uoicx8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkglpm9nl7rcqmp30kt24uoicx8 FOREIGN KEY (lang_to_id) REFERENCES public.languages(id);


--
-- Name: duels fkhvl22ewsb2v5kk6kdtoaab2q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.duels
    ADD CONSTRAINT fkhvl22ewsb2v5kk6kdtoaab2q FOREIGN KEY (lang_to_id) REFERENCES public.languages(id);


--
-- Name: words fkjsgprkeo59pgfrw2peuyrmqux; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.words
    ADD CONSTRAINT fkjsgprkeo59pgfrw2peuyrmqux FOREIGN KEY (language_id) REFERENCES public.languages(id);


--
-- Name: translations fklh7aqx1dxj6h84s2demhyqeea; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translations
    ADD CONSTRAINT fklh7aqx1dxj6h84s2demhyqeea FOREIGN KEY (word_id) REFERENCES public.words(id);


--
-- Name: translations fkotgc3qvl09swiep33s8e2eglo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.translations
    ADD CONSTRAINT fkotgc3qvl09swiep33s8e2eglo FOREIGN KEY (target_language_id) REFERENCES public.languages(id);


--
-- Name: sessions fkruie73rneumyyd1bgo6qw8vjt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fkruie73rneumyyd1bgo6qw8vjt FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict vaOd86Lb50qL42XJwglZSbliLmH7pBTfuDFgBnEUq7UWhqpSv2b8PqROb8KlMq3

